In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json

C:\Users\acer\AppData\Local\Temp\ipykernel_12876\2703235455.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [9]:
df_bangalore = pd.read_excel('Dataset/bangalore_cars.xlsx')
df_bangalore.head()

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [10]:
df_chennai = pd.read_excel('Dataset/chennai_cars.xlsx')
df_chennai.head()

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Minivans', 'k...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [11]:
df_delhi = pd.read_excel('Dataset/delhi_cars.xlsx')
df_delhi.head()

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [12]:
df_hyderabad = pd.read_excel('Dataset/hyderabad_cars.xlsx')
df_hyderabad.head()

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [13]:
df_jaipur = pd.read_excel('Dataset/jaipur_cars.xlsx')
df_jaipur.head()

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [14]:
df_kolkata = pd.read_excel('Dataset/kolkata_cars.xlsx')
df_kolkata.head()

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [15]:
print(df_bangalore.shape)
print(df_chennai.shape)
print(df_delhi.shape)
print(df_hyderabad.shape)
print(df_jaipur.shape)
print(df_kolkata.shape)

(1481, 5)
(1419, 5)
(1485, 5)
(1483, 5)
(1120, 5)
(1381, 5)

In [16]:
# add city column in each dataset to identify their city.
df_bangalore['city'] = 'Bangalore'
df_chennai['city'] = 'Chennai'
df_delhi['city'] = 'Delhi'
df_hyderabad['city'] = 'Hyderabad'
df_jaipur['city'] = 'Jaipur'
df_kolkata['city'] = 'Kolkata'

In [17]:
df_combined = pd.concat([df_bangalore,df_chennai,df_delhi,df_hyderabad,df_jaipur,df_kolkata], axis=0, ignore_index=True)

In [18]:
df_combined.shape

(8369, 6)

In [19]:
df_combined.head()

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links,city
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Bangalore
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,Bangalore
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Bangalore
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,Bangalore
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Bangalore

In [20]:
df_combined.iloc[2,0]

"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', 'km': '11,949', 'transmission': 'Manual', 'ownerNo': 1, 'owner': '1st Owner', 'oem': 'Tata', 'model': 'Tata Tiago', 'modelYear': 2018, 'centralVariantId': 2983, 'variantName': '1.2 Revotron XZ', 'price': '₹ 5.85 Lakh', 'priceActual': '', 'priceSaving': '', 'priceFixedText': None, 'trendingText': {'imgUrl': 'https://stimg.cardekho.com/used-cars/common/icons/trending.svg', 'heading': 'Trending Car!', 'desc': 'High chances of sale in next 6 days'}}"

As we can see all the datasets have same column and data in each column is in json format. Lets Parse each json column to extract relevant information using json library and create new relevant column for e.g fuel_type, milege, seats, etc. we will do this for each column in the combined dataset and the preprocess those columns. we will parse only columns that will be helpful in price prediction.

In [21]:
import ast

# Function to evaluate literal expression
def eval_literal(expression):
    try:
        # Evaluate the literal expression
        return ast.literal_eval(expression)
    except (SyntaxError, ValueError):
        return {}

# Apply the function to 'new_car_detail' column
df_combined['new_car_detail'] = df_combined['new_car_detail'].apply(eval_literal)

# Extract information from 'new_car_detail'
df_combined['Fuel_Type'] = df_combined['new_car_detail'].apply(lambda x: x.get('ft', ''))
df_combined['Transmission'] = df_combined['new_car_detail'].apply(lambda x: x.get('transmission', ''))
df_combined['Owner'] = df_combined['new_car_detail'].apply(lambda x: x.get('owner', ''))
df_combined['OEM'] = df_combined['new_car_detail'].apply(lambda x: x.get('oem', ''))
df_combined['Model'] = df_combined['new_car_detail'].apply(lambda x: x.get('model', ''))
df_combined['Model_Year'] = df_combined['new_car_detail'].apply(lambda x: x.get('modelYear', ''))
df_combined['Price'] = df_combined['new_car_detail'].apply(lambda x: x.get('price', ''))

In [22]:
# Drop the original 'new_car_detail' column
df_combined.drop('new_car_detail', axis=1, inplace=True)

In [23]:
df_combined.head(3)

,new_car_overview,new_car_feature,new_car_specs,car_links,city,Fuel_Type,Transmission,Owner,OEM,Model,Model_Year,Price
0,"{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Bangalore,Petrol,Manual,3rd Owner,Maruti,Maruti Celerio,2015,₹ 4 Lakh
1,"{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,Bangalore,Petrol,Manual,2nd Owner,Ford,Ford Ecosport,2018,₹ 8.11 Lakh
2,"{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Bangalore,Petrol,Manual,1st Owner,Tata,Tata Tiago,2018,₹ 5.85 Lakh

In [24]:
import pandas as pd
import json

# Assuming df_combined is your combined dataset

# Extract information from 'new_car_overview' column
def extract_overview_info(row):
    try:
        data = eval(row['new_car_overview'])
        top_data = data['top']
        info_dict = {item['key'].replace(' ', '_'): item['value'] for item in top_data}
        return info_dict
    except (KeyError, TypeError):
        return {
            'Registration_Year': '',
            'Insurance_Validity': '',
            'Fuel_Type': '',
            'Seats': '',
            'Kms_Driven': '',
            'RTO': '',
            'Ownership': '',
            'Engine_Displacement': '',
            'Transmission': '',
            'Year_of_Manufacture': ''
        }

# Apply the function to create new columns
df_combined[['Registration_Year', 'Insurance_Validity', 'Fuel_Type', 'Seats', 'Kms_Driven', 'RTO',
              'Ownership', 'Engine_Displacement', 'Transmission', 'Year_of_Manufacture']] = \
    df_combined.apply(extract_overview_info, axis=1, result_type='expand')

In [25]:
# Drop the original 'new_car_overview' column
df_combined = df_combined.drop(columns=['new_car_overview'])

In [26]:
df_combined.head(2)

,new_car_feature,new_car_specs,car_links,city,Fuel_Type,Transmission,Owner,OEM,Model,Model_Year,Price,Registration_Year,Insurance_Validity,Seats,Kms_Driven,RTO,Ownership,Engine_Displacement,Year_of_Manufacture
0,"{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Bangalore,Petrol,Manual,3rd Owner,Maruti,Maruti Celerio,2015,₹ 4 Lakh,2015,Third Party insurance,5 Seats,"1,20,000 Kms",KA51,Third Owner,998 cc,2015.0
1,"{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,Bangalore,Petrol,Manual,2nd Owner,Ford,Ford Ecosport,2018,₹ 8.11 Lakh,Feb 2018,Comprehensive,5 Seats,"32,706 Kms",KA05,Second Owner,1497 cc,2018.0

In [27]:
import pandas as pd
import ast

# Extracting data from 'new_car_feature' column
df_combined['new_car_feature'] = df_combined['new_car_feature'].apply(lambda x: {} if pd.isna(x) else ast.literal_eval(x))

# Creating new columns
df_combined['Feature_Heading'] = df_combined['new_car_feature'].apply(lambda x: x.get('heading', ''))
df_combined['Top_Features'] = df_combined['new_car_feature'].apply(lambda x: ', '.join([item['value'] for item in x.get('top', [])]))

# Extracting data from 'data' within 'new_car_feature'
df_combined['Category_Heading'] = df_combined['new_car_feature'].apply(lambda x: x.get('data', [])[0].get('heading', '') if x.get('data') else '')
df_combined['Category_SubHeading'] = df_combined['new_car_feature'].apply(lambda x: x.get('data', [])[0].get('subHeading', '') if x.get('data') else '')
df_combined['Category_Features'] = df_combined['new_car_feature'].apply(lambda x: ', '.join([item['value'] for item in x.get('data', [])[0].get('list', [])]) if x.get('data') else '')

In [28]:
# Dropping the original 'new_car_feature' column if needed
df_combined = df_combined.drop(columns=['new_car_feature'])

In [29]:
df_combined.head(2)

,new_car_specs,car_links,city,Fuel_Type,Transmission,Owner,OEM,Model,Model_Year,Price,...,Kms_Driven,RTO,Ownership,Engine_Displacement,Year_of_Manufacture,Feature_Heading,Top_Features,Category_Heading,Category_SubHeading,Category_Features
0,"{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Bangalore,Petrol,Manual,3rd Owner,Maruti,Maruti Celerio,2015,₹ 4 Lakh,...,"1,20,000 Kms",KA51,Third Owner,998 cc,2015.0,Features,"Power Steering, Power Windows Front, Air Condi...",Comfort & Convenience,Comfort,"Power Steering, Power Windows Front, Power Win..."
1,"{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,Bangalore,Petrol,Manual,2nd Owner,Ford,Ford Ecosport,2018,₹ 8.11 Lakh,...,"32,706 Kms",KA05,Second Owner,1497 cc,2018.0,Features,"Power Steering, Power Windows Front, Air Condi...",Comfort & Convenience,Comfort,"Power Steering, Power Windows Front, Power Win..."

In [30]:
# lets see new_car_specs column data structure
df_combined.iloc[0,0]

"{'heading': 'Specifications', 'top': [{'key': 'Mileage', 'value': '23.1 kmpl'}, {'key': 'Engine', 'value': '998 CC'}, {'key': 'Max Power', 'value': '67.04bhp'}, {'key': 'Torque', 'value': '90Nm'}, {'key': 'Seats', 'value': '5'}], 'data': [{'heading': 'Engine and Transmission', 'subHeading': 'Engine', 'list': [{'key': 'Color', 'value': 'White'}, {'key': 'Engine Type', 'value': 'K10B Engine'}, {'key': 'Displacement', 'value': '998'}, {'key': 'Max Power', 'value': '67.04bhp@6000rpm'}, {'key': 'Max Torque', 'value': '90Nm@3500rpm'}, {'key': 'No of Cylinder', 'value': 3}, {'key': 'Values per Cylinder', 'value': 4}, {'key': 'Value Configuration', 'value': 'DOHC'}, {'key': 'Fuel Suppy System', 'value': 'MPFi'}, {'key': 'BoreX Stroke', 'value': '73 X 82 mm'}, {'key': 'Compression Ratio', 'value': '11.0:1'}, {'key': 'Turbo Charger', 'value': 'No'}, {'key': 'Super Charger', 'value': 'No'}]}, {'heading': 'Dimensions & Capacity', 'subHeading': 'Dimensions', 'list': [{'key': 'Length', 'value': '3715mm'}, {'key': 'Width', 'value': '1635mm'}, {'key': 'Height', 'value': '1565mm'}, {'key': 'Wheel Base', 'value': '2425mm'}, {'key': 'Front Tread', 'value': '1420mm'}, {'key': 'Rear Tread', 'value': '1410mm'}, {'key': 'Kerb Weight', 'value': '835kg'}, {'key': 'Gross Weight', 'value': '1250kg'}]}, {'heading': 'Miscellaneous', 'subHeading': 'Miscellaneous', 'list': [{'key': 'Gear Box', 'value': '5 Speed '}, {'key': 'Drive Type', 'value': 'FWD'}, {'key': 'Seating Capacity', 'value': '5'}, {'key': 'Steering Type', 'value': 'Power'}, {'key': 'Turning Radius', 'value': '4.7 metres'}, {'key': 'Front Brake Type', 'value': 'Ventilated Disc'}, {'key': 'Rear Brake Type', 'value': 'Drum'}, {'key': 'Top Speed', 'value': '150 Kmph'}, {'key': 'Acceleration', 'value': '15.05 Seconds'}, {'key': 'Tyre Type', 'value': 'Tubeless, Radial'}, {'key': 'No Door Numbers', 'value': '5'}, {'key': 'Cargo Volumn', 'value': '235-litres'}]}], 'commonIcon': ''}"

In [31]:
import ast

# Function to convert string representation to dictionary using ast.literal_eval
def convert_to_dict(specs_str):
    try:
        return ast.literal_eval(specs_str)
    except (SyntaxError, ValueError):
        return {}

# Convert 'new_car_specs' column to actual dictionaries
df_combined['new_car_specs'] = df_combined['new_car_specs'].apply(convert_to_dict)

# Function to extract values from 'top' or 'data' list based on 'key'
def extract_value(specs_dict, key):
    for section in ['top', 'data']:
        items = specs_dict.get(section, [])
        if isinstance(items, list):
            for item in items:
                if isinstance(item, dict) and item.get('key') == key:
                    return item.get('value')
        elif isinstance(items, dict) and items.get('key') == key:
            return items.get('value')
    return None

# Extract and create new columns
df_combined['Mileage'] = df_combined['new_car_specs'].apply(lambda x: extract_value(x, 'Mileage'))
df_combined['Engine'] = df_combined['new_car_specs'].apply(lambda x: extract_value(x, 'Engine'))
df_combined['Max_Power'] = df_combined['new_car_specs'].apply(lambda x: extract_value(x, 'Max Power'))
df_combined['Torque'] = df_combined['new_car_specs'].apply(lambda x: extract_value(x, 'Torque'))
df_combined['Seats'] = df_combined['new_car_specs'].apply(lambda x: extract_value(x, 'Seats'))

In [32]:
# drop original car_specs column
df_combined = df_combined.drop(columns='new_car_specs')

In [33]:
df_combined.head(3)

,car_links,city,Fuel_Type,Transmission,Owner,OEM,Model,Model_Year,Price,Registration_Year,...,Year_of_Manufacture,Feature_Heading,Top_Features,Category_Heading,Category_SubHeading,Category_Features,Mileage,Engine,Max_Power,Torque
0,https://www.cardekho.com/used-car-details/used...,Bangalore,Petrol,Manual,3rd Owner,Maruti,Maruti Celerio,2015,₹ 4 Lakh,2015,...,2015.0,Features,"Power Steering, Power Windows Front, Air Condi...",Comfort & Convenience,Comfort,"Power Steering, Power Windows Front, Power Win...",23.1 kmpl,998 CC,67.04bhp,90Nm
1,https://www.cardekho.com/buy-used-car-details/...,Bangalore,Petrol,Manual,2nd Owner,Ford,Ford Ecosport,2018,₹ 8.11 Lakh,Feb 2018,...,2018.0,Features,"Power Steering, Power Windows Front, Air Condi...",Comfort & Convenience,Comfort,"Power Steering, Power Windows Front, Power Win...",17 kmpl,1497 CC,121.31bhp,150Nm
2,https://www.cardekho.com/used-car-details/used...,Bangalore,Petrol,Manual,1st Owner,Tata,Tata Tiago,2018,₹ 5.85 Lakh,Sept 2018,...,2018.0,Features,"Power Steering, Power Windows Front, Air Condi...",Comfort & Convenience,Comfort,"Power Steering, Power Windows Front, Power Win...",23.84 kmpl,1199 CC,84bhp,114Nm

In [34]:
df_combined.to_csv('combined_data.csv', index=False)